site_name: 'HyperMake'
site_description: 'Parameterized workflow manager'
site_author: 'Tongfei Chen'
copyright: 'Copyright &copy; 2020-2024 Tongfei Chen'


theme:
  name: material
  palette:
    scheme: default
    primary: 'blue grey'
    accent: grey
  font:
    text: 'Inter'
    code: 'Noto Sans Mono'

repo_name: 'ctongfei/hypermake'
repo_url: 'https://github.com/ctongfei/hypermake'

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

nav:
  - 'Tutorial':
      - "Hello, world!": 'tutorial/hello.md'
      - "Inputs & outputs": 'tutorial/compose.md'
      - "Parameters": 'tutorial/branch.md'
      - "Parameterized pipelines": 'tutorial/parameterized-compose.md'
      - "Subroutines": 'tutorial/subroutines.md'
      - "Decorators": 'tutorial/decorators.md'
      - "Packages": 'tutorial/packages.md'
      - "Modules": 'tutorial/modules.md'
      - "File systems": 'tutorial/filesys.md'
  - 'Library Reference':
      - "Std": 'stdlib/std.md'
      - "AWS": 'stdlib/aws.md'
      - "Azure": 'stdlib/az.md'
      - "Conda": 'stdlib/conda.md'
      - "SSH": 'stdlib/ssh.md'